name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ✅ Clone the repository
        uses: actions/checkout@v4

      - name: 🐙 Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 🔐 Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 🛠️ Build and push Web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.web
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/creda-wallet:web-latest

      - name: 🛠️ Build and push Bank Webhook image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile.webhook
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/creda-wallet:webhook-latest
